//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamaPijeSama.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DamaPijeSama.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players in this game:.
        /// </summary>
        internal static string AboutGameLbl1 {
            get {
                return ResourceManager.GetString("AboutGameLbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards played: .
        /// </summary>
        internal static string AboutGameLbl2 {
            get {
                return ResourceManager.GetString("AboutGameLbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game length: .
        /// </summary>
        internal static string AboutGameLbl3 {
            get {
                return ResourceManager.GetString("AboutGameLbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Developer.
        /// </summary>
        internal static string AboutMeLabel {
            get {
                return ResourceManager.GetString("AboutMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author and links.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen Drinks Alone.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a bug?.
        /// </summary>
        internal static string BugLabel1 {
            get {
                return ResourceManager.GetString("BugLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report it to the aforementioned e-mail describing it as best you can..
        /// </summary>
        internal static string BugLabel2 {
            get {
                return ResourceManager.GetString("BugLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re doing that too quickly. Slow down..
        /// </summary>
        internal static string CardChangeError {
            get {
                return ResourceManager.GetString("CardChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLangBtn {
            get {
                return ResourceManager.GetString("ChangeLangBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions are coming in the next version!.
        /// </summary>
        internal static string ComingSoonMsg {
            get {
                return ResourceManager.GetString("ComingSoonMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactLabel {
            get {
                return ResourceManager.GetString("ContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck shuffled and reset..
        /// </summary>
        internal static string DeckShuffledMsg {
            get {
                return ResourceManager.GetString("DeckShuffledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ashamed. Delete history.
        /// </summary>
        internal static string DeleteHistoryBtn {
            get {
                return ResourceManager.GetString("DeleteHistoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game history deleted..
        /// </summary>
        internal static string DeleteHistoryMsg {
            get {
                return ResourceManager.GetString("DeleteHistoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not gonna drink alone are you?.
        /// </summary>
        internal static string DeletePlayerError {
            get {
                return ResourceManager.GetString("DeletePlayerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deck is empty!.
        /// </summary>
        internal static string EmptyDeckMsg {
            get {
                return ResourceManager.GetString("EmptyDeckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVERYBODY DRINKS.
        /// </summary>
        internal static string EverybodyDrinksMsg {
            get {
                return ResourceManager.GetString("EverybodyDrinksMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Or you drank too much....
        /// </summary>
        internal static string GamesLoadingError {
            get {
                return ResourceManager.GetString("GamesLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games.
        /// </summary>
        internal static string GamesString {
            get {
                return ResourceManager.GetString("GamesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string GameString {
            get {
                return ResourceManager.GetString("GameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong there :( Try again or contact the developer..
        /// </summary>
        internal static string GeneralDBError {
            get {
                return ResourceManager.GetString("GeneralDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :/.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryBtn {
            get {
                return ResourceManager.GetString("HistoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games will appear here once you start playing.
        /// </summary>
        internal static string HistoryPageEmpty {
            get {
                return ResourceManager.GetString("HistoryPageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play history.
        /// </summary>
        internal static string HistoryPageTitle {
            get {
                return ResourceManager.GetString("HistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik postavljen na Hrvatski.
        /// </summary>
        internal static string LangCroMsg {
            get {
                return ResourceManager.GetString("LangCroMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language set to English.
        /// </summary>
        internal static string LangEngMsg {
            get {
                return ResourceManager.GetString("LangEngMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t chosen a language.
        /// </summary>
        internal static string LangSelectError {
            get {
                return ResourceManager.GetString("LangSelectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least give all the players a nickname....
        /// </summary>
        internal static string NicknameError {
            get {
                return ResourceManager.GetString("NicknameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game was played with no players.
        /// </summary>
        internal static string NoPlayersGame {
            get {
                return ResourceManager.GetString("NoPlayersGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string PlayerNameDefault {
            get {
                return ResourceManager.GetString("PlayerNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameless.
        /// </summary>
        internal static string PlayerNameEmpty {
            get {
                return ResourceManager.GetString("PlayerNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string PlayersBtn {
            get {
                return ResourceManager.GetString("PlayersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players: swipe down.
        /// </summary>
        internal static string PlayersLbl {
            get {
                return ResourceManager.GetString("PlayersLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many drinkers?.
        /// </summary>
        internal static string PlayersPageTitle {
            get {
                return ResourceManager.GetString("PlayersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string PlayerString {
            get {
                return ResourceManager.GetString("PlayerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstart.
        /// </summary>
        internal static string QuickstartBtn {
            get {
                return ResourceManager.GetString("QuickstartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart: swipe up.
        /// </summary>
        internal static string RestartLbl {
            get {
                return ResourceManager.GetString("RestartLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string SetupBtn1 {
            get {
                return ResourceManager.GetString("SetupBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string SetupBtn2 {
            get {
                return ResourceManager.GetString("SetupBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string SetupBtn3 {
            get {
                return ResourceManager.GetString("SetupBtn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        internal static string SocialNetworksLabel {
            get {
                return ResourceManager.GetString("SocialNetworksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next: swipe right.
        /// </summary>
        internal static string SwipeRightLbl {
            get {
                return ResourceManager.GetString("SwipeRightLbl", resourceCulture);
            }
        }
    }
}
